### ISSUE TITLE
monaco-editor-manager could not found on https://registry.npmjs.org

### ISSUE THREAD

**Issue by aqssxlzc** [remcohaszing/monaco-worker-manager#1]
Try to add monaco-editor-manager by
 `npm install monaco-editor-manager`

npm give the follow response:

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/monaco-editor-manager - Not found
npm ERR! 404 
npm ERR! 404  'monaco-editor-manager@*' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by remcohaszing** [comment]
I see, it’s a typo in the readme. The package is called `monaco-worker-manager`. Would you like to provide a PR to fix it?

**Comment by aqssxlzc** [comment]
with pleasure. :smile:
